from django.urls import path
#djangoモジュールのurlsクラスのpath関数をimport

from . import views


app_name='blog'
#他のアプリで
urlpatterns = [
    #path('',views.IndexView.as_view(),name='index'),
    #path('Top',views.Top,name='Top'),
    #path('top_page',views.top_page,name='top_page'),
    #pathは関数、path(URL,関数またはクラス、name=URL名称）
    #nameで指定したURL名称は主に以下３つのパターンで使用される。
    #name関数を使うメリットはURLを変更しても、他ファイルの変更必要なし
    #1.テンプレート：aタグのhref属性で指定
    #2.views.py:redirectで使用
    #3.views.py:reverseで使用
    #path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    #path(int整数の型を定義、実行する関数,name＝URL名称）
    #URLに数字を入力する→urlpatternsと一致する引数を探す→隣の関数を呼び出す→関数内の動作を実施する
    #path('<int:pk>/results/',views.ResultsView.as_view(),name='results'),
    #path('<int:question_id>/vote/',views.vote,name='vote'),
    path('',views.IndexView.as_view(),name='index'),
    path('trivia-greatman',views.trivia_greatman,name='trivia_greatman'),
    path('trivia-greatman1',views.trivia_greatman1,name='trivia_greatman1'),
    path('trivia-summary1',views.trivia_summary1,name='trivia_summary1'),
    path('trivia-rich1',views.trivia_rich1,name='trivia_rich1'),
    path('trivia-athlete-rich1', views.trivia_athlete_rich1, name='trivia_athlete_rich1'),
    path('trivia-artist-rich1', views.trivia_artist_rich1, name='trivia_artist_rich1'),
    path('trivia-soccer-goal1', views.trivia_soccer_goal1, name='trivia_soccer_goal1'),
    path('trivia-comedian1', views.trivia_comedian1, name='trivia_comedian1'),
    path('trivia-game',views.trivia_game,name='trivia_game'),
    path('trivia-game1', views.trivia_game1, name='trivia_game1'),
    path('trivia-baseball-homerun1', views.trivia_baseball_homerun1, name='trivia_baseball_homerun1'),
    path('trivia-potatochips1', views.trivia_potatochips1, name='trivia_potatochips1'),
    path('trivia-population1', views.trivia_population1, name='trivia_population1'),
    path('trivia-game',views.trivia_game,name='trivia_game'),
    path('trivia-game1', views.trivia_game1, name='trivia_game1'),
    path('trivia-break',views.trivia_break,name='trivia_break'),
    path('trivia-break1', views.trivia_break1, name='trivia_break1'),
    path('diary-230110',views.diary_230110,name='diary_230110'),
    path('diary-summary',views.diary_summary,name='diary_summary'),
    path('diary-230114',views.diary_230114,name='diary_230114'),
    path('diary-230115',views.diary_230115,name='diary_230115'),
    path('humor-seiza1',views.humor_seiza1,name='humor_seiza1'),
    path('humor-busaiku1',views.humor_busaiku1,name='humor_busaiku1'),
    path('humor-ladytalk1',views.humor_ladytalk1,name='humor_ladytalk1'),
    path('humor-party1',views.humor_party1,name='humor_party1'),
    path('humor-smart1',views.humor_smart1,name='humor_smart1'),
    path('humor-macchan1',views.humor_macchan1,name='humor_macchan1'),
    path('humor-propose1',views.humor_propose1,name='humor_propose1'),
    path('humor-nickname1',views.humor_nickname1,name='humor_nickname1'),
    path('humor-yourself1',views.humor_yourself1,name='humor_yourself1'),
    path('humor-positive1',views.humor_positive1,name='humor_positive1'),
    path('humor-life1',views.humor_life1,name='humor_life1'),
    path('humor-soccer-tsukkomi1', views.humor_soccer_tsukkomi1, name='humor_soccer_tsukkomi1'),
    path('humor-baseball-tsukkomi1', views.humor_baseball_tsukkomi1, name='humor_baseball_tsukkomi1'),
    path('humor-fart1',views.humor_fart1,name='humor_fart1'),
    path('humor-nosehair1',views.humor_nosehair1,name='humor_nosehair1'),
    path('humor-badbreath1', views.humor_badbreath1, name='humor_badbreath1'),
    path('humor-bodyodor1',views.humor_bodyodor1,name='humor_bodyodor1'),
    path('humor-footodor1',views.humor_footodor1,name='humor_footodor1'),
    path('humor-booger1',views.humor_booger1,name='humor_booger1'),
    path('humor-silent1',views.humor_silent1,name='humor_silent1'),
    path('humor-boss1',views.humor_boss1,name='humor_boss1'),
    path('humor-junior1',views.humor_junior1,name='humor_junior1'),
    path('humor-reunion1',views.humor_reunion1,name='humor_reunion1'),
    path('humor-makeup1',views.humor_makeup1,name='humor_makeup1'),
    path('humor-parent1',views.humor_parent1,name='humor_parent1'),
    path('humor-friends1',views.humor_friends1,name='humor_friends1'),
    path('humor-toilet1',views.humor_toilet1,name='humor_toilet1'),
    path('humor-ero1',views.humor_ero1,name='humor_ero1'),
    path('humor-lame1',views.humor_lame1,name='humor_lame1'),
    path('humor-damage1',views.humor_damage1,name='humor_damage1'),
    path('humor-frustrate1',views.humor_frustrate1,name='humor_frustrate1'),
    path('humor-which1',views.humor_which1,name='humor_which1'),
    path('humor-reason1',views.humor_reason1,name='humor_reason1'),
    path('humor-love1',views.humor_love1,name='humor_love1'),
    path('humor-type1',views.humor_type1,name='humor_type1'),
    path('humor-blood1',views.humor_blood1,name='humor_blood1'),
    path('humor-like1',views.humor_like1,name='humor_like1'),
    path('humor-cinema1', views.humor_cinema1, name='humor_cinema1'),
    path('humor-cool1', views.humor_cool1, name='humor_cool1'),
    path('humor-deny1',views.humor_deny1,name='humor_deny1'),
    path('humor-hobby1',views.humor_hobby1,name='humor_hobby1'),
    path('humor-holiday1',views.humor_holiday1,name='humor_holiday1'),
    path('humor-fetish1',views.humor_fetish1,name='humor_fetish1'),
    path('humor-job1',views.humor_job1,name='humor_job1'),
    path('humor-bye1', views.humor_bye1, name='humor_bye1'),
    path('humor-late1',views.humor_late1,name='humor_late1'),
    path('humor-birthplace1', views.humor_birthplace1, name='humor_birthplace1'),
    path('humor-dream1', views.humor_dream1, name='humor_dream1'),
    path('humor-deep1', views.humor_deep1, name='humor_deep1'),
    path('humor-thoughts1', views.humor_thoughts1, name='humor_thoughts1'),
    path('humor-stress1', views.humor_stress1, name='humor_stress1'),
    path('humor-lookup1', views.humor_lookup1, name='humor_lookup1'),
    path('humor-artist1', views.humor_artist1, name='humor_artist1'),
    path('humor-sports1', views.humor_sports1, name='humor_sports1'),
    path('humor-flash1', views.humor_flash1, name='humor_flash1'),
    path('humor-salary11', views.humor_salary11, name='humor_salary11'),
    path('humor-salary12', views.humor_salary12, name='humor_salary12'),
    path('humor-salary13', views.humor_salary13, name='humor_salary13'),
    path('humor-salary14', views.humor_salary14, name='humor_salary14'),
    path('humor-summary0', views.humor_summary0, name='humor_summary0'),
    path('humor-summary1', views.humor_summary1, name='humor_summary1'),
    path('humor-summary2', views.humor_summary2, name='humor_summary2'),
    path('humor-summary3', views.humor_summary3, name='humor_summary3'),
    path('humor-summary4', views.humor_summary4, name='humor_summary4'),
    path('humor-summary5', views.humor_summary5, name='humor_summary5'),
    path('humor-summary6', views.humor_summary6, name='humor_summary6'),
    path('life-kabu1',views.life_kabu1,name='life_kabu1'),
    path('life-coin1',views.life_coin1,name='life_coin1'),
    path('life-comic1',views.life_comic1,name='life_comic1'),
    path('life-english1',views.life_english1,name='life_english1'),
    path('life-asp1',views.life_asp1,name='life_asp1'),
    path('life-summary1', views.life_summary1, name='life_summary1'),
    path('life-fx1', views.life_fx1, name='life_fx1'),
    path('fashion-summary1', views.fashion_summary1, name='fashion_summary1'),
    path('fashion-summary2', views.fashion_summary2, name='fashion_summary2'),
    path('fashion-summary3', views.fashion_summary3, name='fashion_summary3'),
    path('fashion-glasses1',views.fashion_glasses1,name='fashion_glasses1'),
    path('fashion-trainer1',views.fashion_trainer1,name='fashion_trainer1'),
    path('fashion-sneaker1',views.fashion_sneaker1,name='fashion_sneaker1'),
    path('fashion-jeans1',views.fashion_jeans1,name='fashion_jeans1'),
    path('fashion-auter1',views.fashion_auter1,name='fashion_auter1'),
    path('fashion-poro1', views.fashion_poro1, name='fashion_poro1'),
    path('fashion-tshirt1',views.fashion_tshirt1,name='fashion_tshirt1'),
    path('fashion-parka1',views.fashion_parka1,name='fashion_parka1'),
    path('fashion-under1',views.fashion_under1,name='fashion_under1'),
    path('fashion-cap1',views.fashion_cap1,name='fashion_cap1'),
    path('fashion-socks1',views.fashion_socks1,name='fashion_socks1'),
    path('fashion-watch1',views.fashion_watch1,name='fashion_watch1'),
    path('fashion-suit1', views.fashion_suit1, name='fashion_suit1'),
    path('fashion-chino1',views.fashion_chino1,name='fashion_chino1'),
    path('fashion-skiny1', views.fashion_skiny1, name='fashion_skiny1'),
    path('fashion-tapere1',views.fashion_tapere1,name='fashion_tapere1'),
    path('fashion-cago1',views.fashion_cago1,name='fashion_cago1'),
    path('fashion-slacks1',views.fashion_slacks1,name='fashion_slacks1'),
    path('fashion-easy1',views.fashion_easy1,name='fashion_easy1'),
    path('fashion-outer-kinds1',views.fashion_outer_kinds1,name='fashion_outer_kinds1'),
    path('fashion-jacket-kinds1',views.fashion_jacket_kinds1,name='fashion_jacket_kinds1'),
    path('fashion-pants-kinds1',views.fashion_pants_kinds1,name='fashion_pants_kinds1'),
    path('fashion-tshirt-kinds-neck1', views.fashion_tshirt_kinds_neck1, name='fashion_tshirt_kinds_neck1'),
    path('fashion-swimsuit1',views.fashion_swimsuit1,name='fashion_swimsuit1'),
    path('ads.txt',views.ads,name='ads.txt'),

]